import React, { useState, useEffect, useRef } from 'react';
import { Plus, Edit2, Trash2, Download, FileText, Search, Image as ImageIcon, Mail, Share2, X } from 'lucide-react';
import * as XLSX from 'xlsx';
import ExportPngTemplate from './ExportPngTemplate';
import api from '../api';
import { useAlert } from '../context/AlertContext';

export default function CardlogList({ cardlogs, loading, onNavigate, refreshLogs }) {
  const [searchTerm, setSearchTerm] = useState('');
  const { showAlert, closeAlert } = useAlert();
  const currentUser = JSON.parse(localStorage.getItem('ches_user') || '{}');
  const isAdmin = currentUser.role === 'administrator/dev';
  const permissions = currentUser.permissions || [];
  
  // If user has 1h restriction, we use that. If they only have unlimited edit, we use that.
  // If admin accidentally checked both, treat it as restricted to 1h to be safe.
  const has1hEdit = permissions.includes('cardlog_edit_1h');
  const hasUnlimitedEdit = permissions.includes('cardlog_edit');
  const canEditAny = isAdmin || (hasUnlimitedEdit && !has1hEdit);
  const canEdit1h = !isAdmin && has1hEdit;
  
  const canDelete = isAdmin || permissions.includes('cardlog_delete');
  const canExport = isAdmin || permissions.includes('cardlog_export');
  const canExportPng = isAdmin || permissions.includes('cardlog_export_png');
  const canResendEmail = isAdmin || permissions.includes('resend_email_notification');

  const [activeExportRow, setActiveExportRow] = useState(null);
  const [exportedImage, setExportedImage] = useState(null);
  const [exportedBlob, setExportedBlob] = useState(null);
  const [exportFilename, setExportFilename] = useState('');
  const exportRef = useRef(null);

  const CHECKLIST_ITEMS = [
    'Lampu Depan', 'Lampu Belakang', 'Ban Depan', 'Ban Belakang', 
    'Klakson', 'Alarm Mundur', 'Rem Jalan', 'Rem Parkir', 
    'Sabuk Pengaman', 'Kebersihan'
  ];

  useEffect(() => {
    if (activeExportRow && exportRef.current) {
      const exportImage = async () => {
        try {
          const { toPng } = await import('html-to-image');
          const dataUrl = await toPng(exportRef.current, { backgroundColor: '#ffffff', pixelRatio: 2, skipFonts: true });
          
          // Convert Data URL to Blob immediately for iOS compatibility
          const arr = dataUrl.split(',');
          const mime = arr[0].match(/:(.*?);/)[1];
          const bstr = atob(arr[1]);
          let n = bstr.length;
          const u8arr = new Uint8Array(n);
          while(n--){
              u8arr[n] = bstr.charCodeAt(n);
          }
          const blob = new Blob([u8arr], {type: mime});
          const blobUrl = URL.createObjectURL(blob);
          
          setExportedBlob(blob);
          setExportedImage(blobUrl);
          setExportFilename(`Cardlog_${activeExportRow.id}_${activeExportRow.unit_no}.png`);
          
          if (closeAlert) closeAlert(); // Close the loading alert
        } catch (err) {
          console.error(err);
          showAlert('Gagal', 'Terjadi kesalahan saat mengekspor: ' + (err.message || err.toString()), 'error');
        } finally {
          setActiveExportRow(null);
        }
      };
      setTimeout(exportImage, 300); // Give enough time for DOM to render for iOS
    }
  }, [activeExportRow]);

  const handleShare = async () => {
    try {
      const file = new File([exportedBlob], exportFilename, {type: exportedBlob.type});
      
      if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: exportFilename,
          text: 'Laporan Cardlog'
        });
      } else {
        // Close modal first so alert is visible
        setExportedImage(null);
        setTimeout(() => showAlert('Pemberitahuan', 'Fitur Bagikan otomatis memerlukan koneksi aman (HTTPS). Karena Anda menggunakan akses IP lokal (HTTP), fitur ini dimatikan oleh browser.', 'info'), 300);
      }
    } catch (e) {
      console.log('Share failed or cancelled', e);
    }
  };

  const handleDownload = () => {
    const link = document.createElement('a');
    link.download = exportFilename;
    link.href = exportedImage;
    link.click();
  };

  const handleCreateNew = () => {
    showAlert(
      'Buat Laporan Baru',
      'Apakah Anda ingin membuat form laporan baru?',
      'confirm',
      () => onNavigate('form')
    );
  };

  const handleExportToExcelConfirm = () => {
    showAlert(
      'Download Excel',
      'Mulai proses pengunduhan laporan ke format Excel?',
      'confirm',
      () => handleExportToExcel()
    );
  };

  const handleExportToExcel = () => {
    if (!cardlogs || cardlogs.length === 0) {
      return showAlert('Peringatan', 'Tidak ada data untuk diexport', 'warning');
    }
    
    const excelData = [];
    
    // Metadata Header
    excelData.push(['Audit Report: Cardlog Operations']);
    excelData.push(['Generated By:', currentUser.full_name || currentUser.username]);
    excelData.push(['Date:', new Date().toLocaleDateString()]);
    excelData.push(['Time:', new Date().toLocaleTimeString()]);
    excelData.push([]);
    
    // Table Headers
    excelData.push([
      'ID', 'Date', 'Shift', 'Operator', 'Unit No', 
      'HM Awal', 'HM Akhir', 'Odometer Awal', 'Odometer Akhir', 'Charging Durasi (Jam)',
      'Lampu Depan', 'Lampu Belakang', 'Ban Depan', 'Ban Belakang', 'Klakson', 
      'Alarm Mundur', 'Rem Jalan', 'Rem Parkir', 'Sabuk Pengaman', 'Kebersihan',
      'Status', 'Jam Mulai Kegiatan', 'Jam Selesai Kegiatan', 'Deskripsi Kegiatan'
    ]);
    
    // Table Rows
    const logsToExport = searchTerm ? cardlogs.filter(log => {
      const term = searchTerm.toLowerCase();
      return log.operator?.toLowerCase().includes(term) || log.unit_no?.toLowerCase().includes(term) || String(log.id).includes(term);
    }) : cardlogs;

    logsToExport.forEach(log => {
      const baseRowData = [
        `LOG-${log.id}`,
        new Date(log.date).toLocaleDateString(),
        log.shift_no,
        log.operator,
        log.unit_no,
        log.hm_awal || '',
        log.hm_akhir || '',
        log.odometer_awal || '',
        log.odometer_akhir || '',
        log.charging_durasi || '',
        log.lampu_depan || '',
        log.lampu_belakang || '',
        log.ban_depan || '',
        log.ban_belakang || '',
        log.klakson || '',
        log.alarm_mundur || '',
        log.rem_jalan || '',
        log.rem_parkir || '',
        log.sabuk_pengaman || '',
        log.kebersihan || '',
        'Completed'
      ];

      if (log.activities && log.activities.length > 0) {
        // Create 1 row per activity
        log.activities.forEach(act => {
          excelData.push([
            ...baseRowData,
            act.jam_mulai || '',
            act.jam_selesai || '',
            act.deskripsi || ''
          ]);
        });
      } else {
        // No activities, just output the base row with empty activity columns
        excelData.push([...baseRowData, '', '', '']);
      }
    });
    
    // Create Workbook
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(excelData);
    
    // Style column widths
    const wscols = [
      {wch: 10}, {wch: 15}, {wch: 10}, {wch: 20}, {wch: 10}, 
      {wch: 10}, {wch: 10}, {wch: 15}, {wch: 15}, {wch: 22},
      {wch: 15}, {wch: 15}, {wch: 15}, {wch: 15}, {wch: 15}, 
      {wch: 15}, {wch: 15}, {wch: 15}, {wch: 15}, {wch: 15},
      {wch: 15}, {wch: 15}, {wch: 15}, {wch: 40}
    ];
    ws['!cols'] = wscols;
    
    XLSX.utils.book_append_sheet(wb, ws, "Cardlogs");
    
    XLSX.writeFile(wb, `Cardlog_Audit_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  const getTemplateProps = (row) => {
    if (!row) return null;
    const formData = {
      date: new Date(row.date).toISOString().split('T')[0],
      shift: row.shift_no,
      operator: row.operator,
      unitNo: row.unit_no,
      submittedBy: row.submitted_by_name || row.operator
    };
    const checklists = CHECKLIST_ITEMS.reduce((acc, item) => {
      const dbKey = item.toLowerCase().replace(' ', '_');
      const val = row[dbKey];
      let status = 'Baik';
      let notes = '';
      if (val && !['Baik', 'Rusak', 'Error'].includes(val)) {
        status = 'Others';
        notes = val;
      } else if (val) {
        status = val;
      }
      acc[item] = { status, notes };
      return acc;
    }, {});
    const operasional = {
      hmAwal: row.hm_awal, hmAkhir: row.hm_akhir,
      odoAwal: row.odometer_awal, odoAkhir: row.odometer_akhir,
      chargingMulai: row.charging_mulai || '', chargingSelesai: row.charging_selesai || '',
      chargingTotal: row.charging_durasi || 0
    };
    const activities = (row.activities || []).map(act => ({
      jamMulai: act.jam_mulai ? act.jam_mulai.substring(0, 5) : '',
      jamSelesai: act.jam_selesai ? act.jam_selesai.substring(0, 5) : '',
      deskripsi: act.deskripsi
    }));
    return { formData, checklists, operasional, activities, odometerPhoto: row.odometer_photo };
  };

  const templateProps = getTemplateProps(activeExportRow);

  const handleDelete = (id) => {
    showAlert(
      'Konfirmasi Hapus',
      'Yakin ingin menghapus cardlog ini?',
      'confirm',
      async () => {
        try {
          await api.delete(`/cardlogs/${id}`);
          if (refreshLogs) refreshLogs();
          showAlert('Sukses!', 'Cardlog berhasil dihapus', 'success');
        } catch (err) {
          showAlert('Gagal!', 'Gagal menghapus cardlog: ' + (err.response?.data?.message || err.message), 'error');
        }
      }
    );
  };

  const handleResendEmail = async (id, e) => {
    e.stopPropagation();
    showAlert(
      'Konfirmasi Resend',
      'Kirim ulang notifikasi email untuk laporan cardlog ini?',
      'confirm',
      async () => {
        showAlert('Memproses...', 'Sedang mengirim ulang email, mohon tunggu sebentar...', 'loading');
        try {
          const res = await api.post(`/cardlogs/${id}/resend-email`);
          showAlert('Sukses!', res.data.message || 'Email berhasil dikirim ulang.', 'success');
        } catch (err) {
          showAlert('Gagal!', err.response?.data?.message || 'Gagal mengirim ulang email.', 'error');
        }
      }
    );
  };

  const handleEditConfirm = (row, e) => {
    if (e) e.stopPropagation();
    showAlert(
      'Konfirmasi Edit',
      'Apakah Anda yakin ingin mengedit data cardlog ini?',
      'confirm',
      () => onNavigate('edit-cardlog', row)
    );
  };

  const handleExportPngConfirm = (row, e) => {
    if (e) e.stopPropagation();
    showAlert(
      'Konfirmasi Export PNG',
      'Apakah Anda yakin ingin mengekspor data cardlog ini sebagai gambar PNG?',
      'confirm',
      () => {
        showAlert('Memproses...', 'Sedang membuat gambar PNG, mohon tunggu...', 'loading');
        setActiveExportRow(row);
      }
    );
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center space-y-4 sm:space-y-0">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white tracking-tight">Semua Cardlogs</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 font-medium mt-1">Daftar seluruh history operasional unit.</p>
        </div>
        
        <div className="flex items-center bg-gray-100 dark:bg-gray-900 rounded-md px-3 py-2 border border-transparent focus-within:border-[#b52025]/50 transition-colors w-full sm:w-72">
          <Search className="w-4 h-4 text-gray-400 mr-2" />
          <input 
            type="text" 
            placeholder="Search operator, unit, or ID..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="bg-transparent border-none outline-none text-sm w-full text-gray-700 dark:text-gray-200"
          />
        </div>

        <div className="flex space-x-3 w-full sm:w-auto">
          {canExport && (
            <button
              onClick={handleExportToExcelConfirm}
              className="flex items-center px-4 py-2.5 bg-green-600 text-white rounded-md font-bold hover:bg-green-700 transition-colors"
            >
              <Download className="w-5 h-5 mr-1.5" />
              Export Excel
            </button>
          )}
          <button
            onClick={handleCreateNew}
            className="flex items-center px-4 py-2.5 bg-[#b52025] text-white rounded-md font-bold hover:bg-[#8c191c] transition-colors"
          >
            <Plus className="w-5 h-5 mr-1.5" />
            New Cardlog
          </button>
        </div>
      </div>

      <div className="bg-white dark:bg-gray-950 rounded-md border border-gray-200 dark:border-gray-800 overflow-hidden">
        {/* Desktop Table */}
        <div className="overflow-x-auto hidden md:block">
          <table className="min-w-full divide-y divide-gray-100 dark:divide-gray-800">
            <thead className="bg-gray-50/50 dark:bg-gray-900/50">
              <tr>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">ID</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Date</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Shift</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Operator</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Unit</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Submitted By</th>
                <th className="px-6 py-4 text-right text-xs font-bold text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50 dark:divide-gray-800/50">
              {loading ? (
                <tr>
                  <td colSpan="6" className="px-6 py-8 text-center text-sm text-gray-500">Loading cardlogs...</td>
                </tr>
              ) : cardlogs.length === 0 ? (
                <tr>
                  <td colSpan="6" className="px-6 py-8 text-center text-sm text-gray-500">No cardlogs found.</td>
                </tr>
              ) : (
                cardlogs.filter(log => {
                  if (!searchTerm) return true;
                  const term = searchTerm.toLowerCase();
                  return log.operator?.toLowerCase().includes(term) || log.unit_no?.toLowerCase().includes(term) || String(log.id).includes(term);
                }).map((row) => {
                  let isEditable = canEditAny;
                  if (!isEditable && canEdit1h && row.age_minutes !== undefined) {
                    if (parseFloat(row.age_minutes) <= 60 && parseFloat(row.age_minutes) >= 0) {
                      isEditable = true;
                    }
                  }

                  return (
                    <tr 
                      key={row.id} 
                      className="hover:bg-gray-50/50 dark:hover:bg-gray-900/50 transition-colors cursor-pointer"
                      onClick={() => onNavigate('view-cardlog', row)}
                    >
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-gray-900 dark:text-white">#LOG-{row.id}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{new Date(row.date).toLocaleDateString()}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-700 dark:text-gray-300">{row.shift_no}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600 dark:text-gray-400">
                        <div className="flex items-center">
                          <div className="w-6 h-6 rounded-full bg-gray-200 dark:bg-gray-800 text-gray-600 dark:text-gray-300 flex items-center justify-center text-xs font-bold mr-2">
                            {row.operator.charAt(0)}
                          </div>
                          {row.operator}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-bold text-gray-700 dark:text-gray-300">{row.unit_no}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{row.submitted_by_name || '-'}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-right flex justify-end space-x-2" onClick={(e) => e.stopPropagation()}>
                        {!isEditable && (
                          <button onClick={() => onNavigate('view-cardlog', row)} className="p-2 text-green-500 hover:text-green-700 dark:text-green-400 dark:hover:text-green-300 rounded-lg hover:bg-green-50 dark:hover:bg-green-900/20 transition-colors" title="View Cardlog">
                            <FileText className="w-4 h-4" />
                          </button>
                        )}
                        {isEditable && (
                          <button onClick={(e) => handleEditConfirm(row, e)} className="p-2 text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 rounded-lg hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors" title="Edit Cardlog">
                            <Edit2 className="w-4 h-4" />
                          </button>
                        )}
                        {canExportPng && (
                          <button onClick={(e) => handleExportPngConfirm(row, e)} className="p-2 text-indigo-500 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-300 rounded-lg hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors" title="Export PNG">
                            <ImageIcon className="w-4 h-4" />
                          </button>
                        )}
                        {canResendEmail && (
                          <button onClick={(e) => handleResendEmail(row.id, e)} className="p-2 text-yellow-500 hover:text-yellow-700 dark:text-yellow-400 dark:hover:text-yellow-300 rounded-lg hover:bg-yellow-50 dark:hover:bg-yellow-900/20 transition-colors" title="Resend Email">
                            <Mail className="w-4 h-4" />
                          </button>
                        )}
                        {canDelete && (
                          <button onClick={() => handleDelete(row.id)} className="p-2 text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors" title="Hapus Cardlog">
                            <Trash2 className="w-4 h-4" />
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>

        {/* Mobile Cards */}
        <div className="grid grid-cols-1 gap-4 p-4 md:hidden">
          {loading ? (
            <div className="text-center p-4 text-gray-500">Loading cardlogs...</div>
          ) : cardlogs.length === 0 ? (
            <div className="text-center p-4 text-gray-500">No cardlogs found.</div>
          ) : (
            cardlogs.filter(log => {
              if (!searchTerm) return true;
              const term = searchTerm.toLowerCase();
              return log.operator?.toLowerCase().includes(term) || log.unit_no?.toLowerCase().includes(term) || String(log.id).includes(term);
            }).map((row) => {
              let isEditable = canEditAny;
              if (!isEditable && canEdit1h && row.age_minutes !== undefined) {
                if (parseFloat(row.age_minutes) <= 60 && parseFloat(row.age_minutes) >= 0) {
                  isEditable = true;
                }
              }

              return (
                <div 
                  key={row.id}
                  className="bg-gray-50 dark:bg-gray-900 rounded-md p-4 border border-gray-200 dark:border-gray-800 flex flex-col space-y-3 cursor-pointer"
                  onClick={() => onNavigate('view-cardlog', row)}
                >
                  <div className="flex justify-between items-start">
                    <div>
                      <span className="text-xs font-bold text-gray-500 uppercase block mb-1">ID & Date</span>
                      <div className="text-sm font-semibold text-gray-900 dark:text-white">#LOG-{row.id}</div>
                      <div className="text-xs text-gray-500">{new Date(row.date).toLocaleDateString()}</div>
                    </div>
                    <div className="text-right">
                      <span className="text-xs font-bold text-gray-500 uppercase block mb-1">Unit & Shift</span>
                      <div className="text-sm font-bold text-[#b52025]">{row.unit_no}</div>
                      <div className="text-xs font-medium text-gray-700 dark:text-gray-300">{row.shift_no}</div>
                    </div>
                  </div>
                  
                  <div className="pt-3 border-t border-gray-200 dark:border-gray-800">
                    <span className="text-xs font-bold text-gray-500 uppercase block mb-1">Operator</span>
                    <div className="flex items-center text-sm font-medium text-gray-800 dark:text-gray-200">
                      <div className="w-5 h-5 rounded-full bg-gray-200 dark:bg-gray-800 text-gray-600 dark:text-gray-300 flex items-center justify-center text-[10px] font-bold mr-2">
                        {row.operator.charAt(0)}
                      </div>
                      {row.operator}
                    </div>
                  </div>

                  <div className="pt-3 border-t border-gray-200 dark:border-gray-800">
                    <span className="text-xs font-bold text-gray-500 uppercase block mb-1">Submitted By</span>
                    <div className="text-sm font-medium text-gray-600 dark:text-gray-400">
                      {row.submitted_by_name || '-'}
                    </div>
                  </div>

                  <div className="flex justify-end space-x-2 pt-3 border-t border-gray-200 dark:border-gray-800 mt-2" onClick={(e) => e.stopPropagation()}>
                    {!isEditable && (
                      <button onClick={() => onNavigate('view-cardlog', row)} className="p-2 text-green-500 bg-green-50 dark:bg-green-900/20 rounded-md" title="View">
                        <FileText className="w-4 h-4" />
                      </button>
                    )}
                    {isEditable && (
                      <button onClick={(e) => handleEditConfirm(row, e)} className="p-2 text-blue-500 bg-blue-50 dark:bg-blue-900/20 rounded-md" title="Edit">
                        <Edit2 className="w-4 h-4" />
                      </button>
                    )}
                    {canExportPng && (
                      <button onClick={(e) => handleExportPngConfirm(row, e)} className="p-2 text-indigo-500 bg-indigo-50 dark:bg-indigo-900/20 rounded-md" title="Export PNG">
                        <ImageIcon className="w-4 h-4" />
                      </button>
                    )}
                    {canResendEmail && (
                      <button onClick={(e) => handleResendEmail(row.id, e)} className="p-2 text-yellow-500 bg-yellow-50 dark:bg-yellow-900/20 rounded-md" title="Resend Email">
                        <Mail className="w-4 h-4" />
                      </button>
                    )}
                    {canDelete && (
                      <button onClick={() => handleDelete(row.id)} className="p-2 text-red-500 bg-red-50 dark:bg-red-900/20 rounded-md" title="Delete">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </div>
                </div>
              );
            })
          )}
        </div>
      </div>
      {/* Hidden PNG Template for Export */}
      {activeExportRow && templateProps && (
        <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', pointerEvents: 'none', zIndex: -100 }}>
          <ExportPngTemplate 
            ref={exportRef}
            formData={templateProps.formData}
            checklists={templateProps.checklists}
            operasional={templateProps.operasional}
            activities={templateProps.activities}
            odometerPhoto={templateProps.odometerPhoto}
          />
        </div>
      )}

      {/* Export Result Modal */}
      {exportedImage && (
        <div className="fixed inset-0 z-[120] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-gray-900/80 backdrop-blur-sm" onClick={() => { setExportedImage(null); setExportedBlob(null); URL.revokeObjectURL(exportedImage); }} />
          <div className="relative bg-white dark:bg-gray-900 rounded-md shadow-xl border border-gray-200 dark:border-gray-800 w-full max-w-sm overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="flex justify-between items-center p-4 border-b border-gray-100 dark:border-gray-800">
              <h3 className="font-bold text-gray-900 dark:text-white">PNG Siap!</h3>
              <button onClick={() => { setExportedImage(null); setExportedBlob(null); URL.revokeObjectURL(exportedImage); }} className="p-2 text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="p-6 flex flex-col items-center bg-gray-50 dark:bg-gray-950 pointer-events-auto">
              <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800/30 rounded-md p-3 mb-4 w-full text-center">
                <p className="text-xs text-blue-700 dark:text-blue-400 font-medium leading-relaxed">
                  💡 <strong>Pengguna iPhone / HP:</strong> <br/>
                  Tekan dan tahan (long-press) gambar di bawah ini, lalu pilih <strong>"Simpan ke Galeri"</strong> atau <strong>"Bagikan"</strong>.
                </p>
              </div>

              <img src={exportedImage} alt="Export Preview" style={{ WebkitTouchCallout: 'default', pointerEvents: 'auto', userSelect: 'none', WebkitUserSelect: 'none' }} className="w-full h-auto max-h-64 object-contain shadow-lg border border-gray-200 dark:border-gray-800 mb-6 rounded cursor-pointer" />
              
              <div className="w-full flex flex-col space-y-3">
                {!!navigator.share && (
                  <button 
                    onClick={handleShare} 
                    className="w-full flex justify-center items-center px-4 py-3 bg-green-600 hover:bg-green-700 text-white rounded-md font-bold text-sm transition-colors"
                  >
                    <Share2 className="w-4 h-4 mr-2" />
                    Bagikan Langsung
                  </button>
                )}
                <button 
                  onClick={handleDownload} 
                  className="w-full flex justify-center items-center px-4 py-3 bg-[#b52025] hover:bg-[#8c191c] text-white rounded-md font-bold text-sm transition-colors"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download File
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
